"""Shared monitoring module (metrics, tracing, logging)."""

from forex_trading.shared.monitoring.logging import configure_logging
from forex_trading.shared.monitoring.metrics import (
    ai_agent_latency_seconds,
    ai_drift_alerts_total,
    ai_signal_confidence,
    ai_signals_generated_total,
    broker_connections_total,
    broker_latency_seconds,
    cache_hits_total,
    cache_misses_total,
    circuit_breaker_state,
    db_pool_size,
    http_request_duration_seconds,
    http_requests_in_flight,
    http_requests_total,
    open_positions_count,
    outbox_events_total,
    outbox_latency_seconds,
    portfolio_exposure_pct,
    portfolio_pnl_usd,
    risk_alerts_total,
    risk_assessments_total,
    risk_vetoes_total,
    trade_execution_duration_seconds,
    trade_executions_total,
    trade_fills_total,
    trade_volume_lots,
    websocket_connections_active,
    websocket_messages_total,
)
from forex_trading.shared.monitoring.tracing import (
    configure_tracing,
    get_tracer,
    shutdown_tracing,
)

__all__ = [
    "configure_logging",
    "configure_tracing",
    "get_tracer",
    "shutdown_tracing",
    # Metrics
    "http_requests_total",
    "http_request_duration_seconds",
    "http_requests_in_flight",
    "websocket_connections_active",
    "websocket_messages_total",
    "trade_executions_total",
    "trade_execution_duration_seconds",
    "trade_fills_total",
    "trade_volume_lots",
    "open_positions_count",
    "portfolio_pnl_usd",
    "portfolio_exposure_pct",
    "ai_signals_generated_total",
    "ai_signal_confidence",
    "ai_agent_latency_seconds",
    "ai_drift_alerts_total",
    "circuit_breaker_state",
    "risk_assessments_total",
    "risk_alerts_total",
    "risk_vetoes_total",
    "broker_connections_total",
    "broker_latency_seconds",
    "db_pool_size",
    "cache_hits_total",
    "cache_misses_total",
    "outbox_events_total",
    "outbox_latency_seconds",
]
